### PR TITLE
Check permission for all proxy requests to mlx-api

### PR DESCRIPTION
**Pull request by yhwang**
For all non-GET proxy requests, a valid session is needed when accessing mlx-ui.
Currently, a valid session can only be obtained via `/login`
page. In this change, I also sync up the expiration of userinfo
and session cookies.

Signed-off-by: Yihong Wang <yh.wang@ibm.com>

### CODE REVIEW

**Comment by yhwang** [comment]
This change is for mlx-ui. for mlx-api, we can disable external access and only allow mlx-ui <==> mlx-api.

**Comment by ckadner** [comment]
> This change is for **mlx-ui**. 

> ... for **mlx-api**, we can disable external access and only allow mlx-ui <==> mlx-api.

Can you elaborate? Maybe describe in a new issue?

**Comment by yhwang** [comment]
@ckadner The login mechanism, UI change and this one are for mlx-ui. Now there will be the basic level security/permission check for mlx-ui. However, for mlx-api, it's still open to everyone. I think we can have similar topology as ml-pipeline and ml-pipeline-ui. mlx-api only accepts and process valid requests from authorized components, i.e mlx-ui and block external requests. Then only authorized users who login to mlx-ui can indirectly use mlx-api.

**Comment by yhwang** [comment]
> The MLX API has a Swagger UI which is very handy to check and verify API methods. At least for development and for debugging later, we need to be able to access that.

agree and that's for development and debugging. but for official deployment, it shouldn't be accessed from external for security.

**Comment by Tomcli** [comment]
This feature is useful to block out all the non authorized users to run the api. For dev we can always add the istio auth policy to expose it for general usage.

**Comment by Tomcli** [comment]
e.g. right now I exposed the api to the istio ingress endpoint, so people who authorized via istio ingress can access it https://github.com/machine-learning-exchange/mlx/pull/51/files#diff-c8fed9aeb9c502777ff1ff50931dead8a34e2a16c2ec611e92d4cb4b53145c4eR23-R27

we can extend or disable the istio mutual if we don't want any authorization during dev.

**Comment by Tomcli** [comment]
@yhwang can you rebase this PR. This should be good to go.

**Comment by yhwang** [comment]
@Tomcli  rebased, docker build and verified.

**Pull request merged**
