### PR TITLE
(ui) Add caching for api requests

### PR DESCRIPTION
**Pull request by drewbutlerbb4**
Store request-response pairs in window local storage. If an identical request arises, return the response pair back instead of creating another API call.

Signed-off-by: Andrew-Butler <Andrew.Butler@ibm.com>

### CODE REVIEW

**Comment by yhwang** [comment]
how about using `{ time: new date(), value: doc }` as the caching value, then we can have a setting for TTL to invalidate the cache entry?

**Comment by ckadner** [comment]
@andrew, could you describe how the caching works, i.e.
- when/how invalidate cache
- how long until cached resources get refreshed
- how to force a cache invalidation
- where are the settings/env variables?

Besides updating the PR description, also add that information in the UI README somewhere?

**Comment by ckadner** [comment]
FYI, the asset list call results will give you the `created_at` timestamp of when a resource was last updated:

`/apis/v1alpha1/catalog`
```JSON
{
  "components": [
    {
      "created_at": "2021-05-12T20:49:49Z",
      "description": "Evaluate the adversarial robustness using the Fast Gradient Sign Method of the Adversarial Robustness Toolbox (ART).\nThis is a simple demonstration of how to create evaluations using adversarial methods, and generally it is not recommended\nto evaluate adv",
      "featured": 0,
      "id": "adversarial-robustness-evaluation",
      "metadata": {
        "annotations": {
          "platform": "OpenSource"
        }
      },
      "name": "Adversarial Robustness Evaluation",
      "parameters": [
        {
          "default": "training-dummy",
          "description": "Required. Training model ID",
...
```

**Comment by ckadner** [comment]
Thanks for adding some documentation @drewbutlerbb4. Two more questions :-)
1. I assume this caching is only for `GET` requests (`fetch...`), yes?
2. With React, this cache lives on the MLX-UI pod on the cluster, it is not cached on a per user (browser) basis, right?

**Comment by drewbutlerbb4** [comment]
> Thanks for adding some documentation @drewbutlerbb4. Two more questions :-)
> 
> 1. I assume this caching is only for `GET` requests (`fetch...`), yes?
> 2. With React, this cache lives on the MLX-UI pod on the cluster, it is not cached on a per user (browser) basis, right?

@ckadner
1. It is only for the three most common requests types: `${API}/apis/v1alpha1/${type}/${id}`, `${API}/apis/v1alpha1/${type}/${asset.id}/templates`, and `${API}/apis/v1alpha1/${type}`
2. It is stored in Window.localStorage which is on a per browser basis

**Review by ckadner — APPROVED** [review]
Thanks Andrew. I think this looks good.

@Tomcli @yhwang -- good to merge this?

**Pull request merged**
