### PR TITLE
Add correct description for update_doc_table

### PR DESCRIPTION
**Pull request by ezinneanne**
**Added correct description for update_doc_table**

### CODE REVIEW

**Comment by ckadner** [comment]
Thanks @ezinneanne -- could you sign your commit(s) to make the [DCO check](https://probot.github.io/apps/dco/) pass?

> There are 2 commits incorrectly signed off. This means that the author(s) of these commits failed to include a Signed-off-by line in their commit message.
> 
> To avoid having PRs blocked in the future, always include `Signed-off-by: Author Name <authoremail@example.com>` in every commit message. You can also do this automatically by using the `-s` flag (i.e., `git commit -s`).
>
> 
> Here is how to fix the problem so that this code can be merged.
> **Rebase the branch**
> 
> If you have a local git environment and meet the criteria below, one option is to rebase the branch and add your `Signed-off-by` lines in the new commits. Please note that if others have already begun work based upon the commits in this branch, this solution will rewrite history and may cause serious issues for collaborators ([described in the git documentation](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) under "**The Perils of Rebasing**").
> 
> You should only do this if:
> 
> - You are the only author of the commits in this branch
> - You are absolutely certain nobody else is doing any work based upon this branch
> - There are no empty commits in the branch (for example, a DCO Remediation Commit which was added using `--allow-empty`)
> 
> To add your `Signed-off-by `line to every commit in this branch:
> 
> - Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
> - In your local branch, run: `git rebase HEAD~2 --signoff`
> - Force push your changes to overwrite the branch: `git push --force-with-lease origin new_branch`
> 
> **Summary**
> 
> Commit sha: [88de544](https://github.com/machine-learning-exchange/mlx/pull/329/commits/88de544bdd233d3fefdd31d75e4fab0c5b2f739c), Author: ezinneanne, Committer: ezinneanne; The sign-off is missing.
> Commit sha: [6f3fb9c](https://github.com/machine-learning-exchange/mlx/pull/329/commits/6f3fb9cef57aeb82d9e4d2fe56b4495058174417), Author: ezinneanne, Committer: ezinneanne; The sign-off is missing.

**Review by ckadner — APPROVED** [review]
👍🏻

**Comment by ezinneanne** [comment]
**I just signed off.  Sorry about the mistake**

**Pull request merged**
