### PR TITLE
Expose Minio console in quickstart with Docker Compose

### LINKED ISSUE #133: Minio dashboard no longer works in quickstart with Docker Compose
**Describe the bug**

**To Reproduce**

1. Follow the steps under [/quickstart](https://github.com/machine-learning-exchange/mlx/tree/main/quickstart)
2. Open the URL `localhost:9000` in a browser
3. See error in screenshot below
4. Warning in the `minio` service log

```
API: http://<my IP>:9000  http://127.0.0.1:9000 

Console: http://<my IP>:40843 http://127.0.0.1:40843 

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (40843), please use --console-address ":PORT" to choose a static port.

```

**Expected behavior**

Minio dashboard should open up

**Screenshots**

`localhost:9000/`

image

**Environment**

 - OS: macOS 10.15.6
 - Browser: Firefox, Chrome, Safari
 - MLX Version: f9a05ba

**Additional context**

https://github.com/minio/minio/issues/12660

### PR DESCRIPTION
**Pull request by ckadner**
Add `--console-address ":9001"` to minio service command.

Resolves #133

Signed-off-by: Christian Kadner <ckadner@us.ibm.com>

### CODE REVIEW

**Comment by Tomcli** [comment]
can you add a version tag to the minio image? so that latest minio changes won't break our code immediately in the future.

**Comment by ckadner** [comment]
> can you add a version tag to the minio image? so that latest minio changes won't break our code immediately in the future.

Unfortunately, they don't really have succinct release tags, more like timestamps for new daily releases, i.e. 

[minio/minio:RELEASE.2021-07-08T19-43-25Z](https://hub.docker.com/layers/minio/minio/RELEASE.2021-07-08T19-43-25Z/images/sha256-454a2fb0a10ab4d2880e8353879691337740fe9e1f0d126cdd4271adac92470e?context=explore)

For other widely used Docker images like `python:3.9` or `mysql:5.7` the tags follow a more clear semantic versioning which get updated with fixes but non-breaking API changes.

For `minio` we would be frozen in time. And I am not sure how long the soon to be old daily release tags will be available, although I do see [5 year old version](https://hub.docker.com/r/minio/minio/tags?page=1&ordering=-last_updated).

**Comment by Tomcli** [comment]
The timestamp release tag should be good enough. KFP was also using the timestamp tag before they build their own license compliance minio image.

**Comment by Tomcli** [comment]
> Unfortunately, they don't really have succinct release tags, more like timestamps for daily releases, i.e.

if you see a tag that has `RELEASE` word in it, the build is based on an official minio release rather than a nightly build. Minio hasn't put any version number in their images for several years already.

**Comment by ckadner** [comment]
> The timestamp release tag should be good enough

I added the latest `minio` image tag [`RELEASE.2021-07-12T02-44-53Z`](https://hub.docker.com/layers/minio/minio/RELEASE.2021-07-12T02-44-53Z/images/sha256-daeaae183545d6d6eedee0bc443dfdf260fc05042440ac27d5a50bccff3f05be?context=explore) and tested it works ok

**Comment by Tomcli** [comment]
quick question: only the console is exposed to port 9001? All the other minio api calls still work on port 9000?

**Comment by ckadner** [comment]
> quick question: only the console is exposed to port 9001? All the other minio api calls still work on port 9000?

The minio API remains on port `9000`

**Comment by ckadner** [comment]
Thanks @Tomcli

**Pull request merged**
