### PR TITLE
Update MLX manifests to work with kubeflow 1.3

### PR DESCRIPTION
**Pull request by Tomcli**
note: pipeline api is broken due to #50 

To deploy this, follow either single or multi-user Kubeflow deployment on https://www.kubeflow.org/docs/distributions/ibm/deploy/install-kubeflow-on-iks. Then follow the docs/install-mlx-on-kubeflow.md to install MLX. 

Please be aware that all IKS Kubeflow 1.3 deployment will use the new istio-auth.

### CODE REVIEW

**Comment by drewbutlerbb4** [comment]
Thanks @Tomcli this works for me
/lgtm

**Comment by yhwang** [comment]
one question: does mlx-ui access ml-pipelines directly or go through mlx-api as proxy?

**Comment by Tomcli** [comment]
> one question: does mlx-ui access ml-pipelines directly or go through mlx-api as proxy?

For getting the pipeline, it goes through mlx-api. For rendering the iframe, it goes through ml-pipeline-ui

**Comment by yhwang** [comment]
> For getting the pipeline, it goes through mlx-api. For rendering the iframe, it goes through ml-pipeline-ui

Got it. So for mlx-ui, it only needs to access mlx-api. Because for iframe, it goes from user's browser to ml-pipeline-ui directly.

**Review by ckadner — APPROVED** [review]
/lgtm

Thanks Tommy!

**Pull request merged**
