### PR TITLE
platform specification for ARM/M1 compatability with mysql

### PR DESCRIPTION
**Pull request by BluThaitanium**
Adds docker compatibility for ARM architecture including M1 chips

### CODE REVIEW

**Comment by BluThaitanium** [comment]
Tested and works on M1 MacOS & Ubuntu Linux

**Comment by ckadner** [comment]
Thanks Phu! 

@Zachary-Fernandes -- can you confirm this works on Windows/WSL as well?

**Review by ckadner — APPROVED** [review]
👍🏻

**Comment by ckadner** [comment]
@Zachary-Fernandes -- if you can confirm this works on Windows/WSL as well, please add your `/lgtm`. Thanks

**Comment by Zachary-Fernandes** [comment]
This works for me on Powershell and WSL2. I think it is ready to go.

/lgtm

**Pull request merged**
