### PR TITLE
[WIP] Test Bot Comment permission

### PR DESCRIPTION
**Pull request by Tomcli**
Check whether the bot has permission to delete comments

### CODE REVIEW

**Comment by Tomcli** [comment]
/close
rolled out an new prow image to fix the prow approve plugin

**Comment by ckadner** [comment]
What's the new process for adding/removing labels `/lgtm` and `/approve`

**Comment by Tomcli** [comment]
`/lgtm cancel` and `/approve cancel` will able to remove those 2 labels

**Pull request closed without merging**
