### PR TITLE
Enable the Pipeline catalog assets in Docker Compose without the KFP API

### PR DESCRIPTION
**Pull request by ckadner**
The KFP API cannot run inside a Docker Compose stack (#28). 

As a workaround, if the KFP host is `"UNAVAILABLE"`, the MLX API server 
will store the pipeline metadata in MySQL and the pipeline template in Minio, 
as opposed to relying on the KFP API for that.

Signed-off-by: Christian Kadner <ckadner@us.ibm.com>

### CODE REVIEW

**Review by Tomcli — COMMENTED** [review]
Thanks @ckadner, it looks good to me. Is it possible to split a log message during the API startup to tell the developer they are running with mock pipeline api? Also it would be good to indicate that in the quickstart readme as well.

**Comment by ckadner** [comment]
> ... have a log message during the API startup to tell the developers that they are running with mock pipeline api?

I did not add a "mock" API for KFP. None of the KFP API calls will work. I simply added the code in the MLX API to store the pipeline metadata in MySQL and the pipeline template in Minio.

**Comment by Tomcli** [comment]
> > ... have a log message during the API startup to tell the developers that they are running with mock pipeline api?
> 
> I did not add a "mock" API for KFP. None of the KFP API calls will work. I simply added the code in the MLX API to store the pipeline metadata in MySQL and the pipeline template in Minio.

Sorry I should say mock API for MLX pipelines. If "mock" is not the right word we can say it uses a different implementation for the MLX pipeline API during local dev.

**Comment by ckadner** [comment]
> ... "mock" is not the right word we can say it uses a different implementation for the MLX pipeline API 

I added a few more lines to the `quickstart/README.md`:

> In a Kubernetes cluster deployment of MLX, _Pipelines_ are registered using
the KFP API and metadata storage is managed by KFP. In this Docker Compose
setup the _Pipelines_ are stored in Minio and MySQL by the MLX API server.

Do you think that is sufficient?

**Comment by Tomcli** [comment]
thanks @ckadner 
/lgtm

**Pull request merged**
