### PR TITLE
Disable execution in Docker Compose

### LINKED ISSUE #47: [UI] Disable pipeline run/launch in Docker Compose
When [running MLX with `docker-compose`](https://github.com/machine-learning-exchange/mlx/tree/main/quickstart) the KFP API is [not available](#28).

We need to disable the pipeline run capabilities in the UI when the `REACT_APP_KFP` is not set, or set it to `"UNAVAILABLE"` like for the MLX API:

https://github.com/machine-learning-exchange/mlx/blob/56d5f6f47a7bd66d41fc0b42ce30158db1279b6c/quickstart/docker-compose.yaml#L58

### PR DESCRIPTION
**Pull request by ckadner**
Resolves #47

Signed-off-by: Christian Kadner <ckadner@us.ibm.com>

### CODE REVIEW

**Comment by ckadner** [comment]
@drewbutlerbb4 -- it looks like the UI still shows the launch tab despite the setting `"Execution enabled"` showing 
`"false"` and is toggled off

**Comment by ckadner** [comment]
@yhwang -- FYI

**Comment by drewbutlerbb4** [comment]
Thanks @ckadner, I'll take a look into it

**Comment by yhwang** [comment]
@ckadner after my pr #41, those curl commands would fail. since only admin can access `/settings`. I tested one of your commands against my env, I got this:
```
$ curl -X PUT -H 'Content-Type: application/json' -H 'Accept: application/json' -d '{"Inference Services": false}' -s "${my_mlx_env}/os/settings"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot PUT /os/settings</pre>
</body>
</html>
```

**Comment by yhwang** [comment]
verified these commands in my env. They work properly

**Review by yhwang — APPROVED** [review]

**Comment by ckadner** [comment]
Thanks @yhwang

**Pull request merged**
