### PR TITLE
Add MLX minimum setup

### PR DESCRIPTION
**Pull request by Tomcli**
Add MLX minimum setup (MLX single user with pipeline, Tekton and istio only) for the Acumos team. <del> Currently #91 is blocking the MLX API from running the pipelines (for both single and multi-user) </del> #91 is fixed now

### CODE REVIEW

**Comment by ckadner** [comment]
Hi Tommy, I created a new IKS cluster and will try out your setup

**Comment by ckadner** [comment]
Hi Tommy, can you clarify how this new doc relates to our existing doc [docs/mlx-install-with-kubeflow.md](https://github.com/machine-learning-exchange/mlx/blob/main/docs/mlx-install-with-kubeflow.md)?

**Comment by Tomcli** [comment]
> Hi Tommy, can you clarify how this new doc relates to our existing doc [docs/mlx-install-with-kubeflow.md](https://github.com/machine-learning-exchange/mlx/blob/main/docs/mlx-install-with-kubeflow.md)?

The one Mofi has created includes all Kubeflow components + MLX + datashim. This one in this PR is more for people who want to try MLX with basic pipelines and don't have to worry about auth/storage/namespace etc.

**Comment by Tomcli** [comment]
I'm not exposing this to the main README because this setup is more for people who only want to try out the MLX pipeline feature like the Acumos team and minimize their quota.

**Comment by ckadner** [comment]
So for IKS users, they still need to do the block storage setup before running this `kustomize build`, yes? Anything else pre-requisite?

**Comment by Tomcli** [comment]
> So for IKS users, they still need to do the block storage setup before running this `kustomize build`, yes? Anything else pre-requisite?

For this one there's no storage requirement. They technically iks can use the default nfs for the kfp-tekton mysql because kfp is using mysql 5.7. We only have the storage issue with the auth services and the mysql for metadata and katib only.

**Comment by Tomcli** [comment]
There's actually not many pre-requisite for this deployment other than the Kubernetes cluster and kustomize version. This is why I want to have this minimum setup to share with teams that only want to use MLX pipelines and have very few Kubernetes knowledge.

**Comment by ckadner** [comment]
Two more questions:
1. Should this minimal deployment be prepopulated with the catalog? 
2. Should users be able to launch pipelines and find the pipelinerun results?

**Comment by Tomcli** [comment]
> Two more questions:
> 
> 1. Should this minimal deployment be prepopulated with the catalog?
> 2. Should users be able to launch pipelines and find the pipelinerun results?

1. We don't have to, this deployment is more aimed for people who want to run pure pipelines. We can have some optional pointers on how to import assets, but not installing it by default. This is a minimum setup where we won't have katib, kfserving etc to run most of the Kubeflow related pipelines.
2. Yes, this is why #91 was the blocker. This is single user mode so everyone can run and view pipelines.

You can think of this like a minimum dev setup for teams who want to develop new assets on MLX. If they want to introduce new asset type like acumos marketplace, they can install them after the fact.

**Comment by ckadner** [comment]
> > 2. Should users be able to launch pipelines and find the pipelinerun results?
> 
> 2. Yes, this is why #91 was the blocker. This is single user mode so everyone can run and view pipelines.

After a user launches a pipeline, where can they see the run results, graph, logs, etc? After I launched the Flip-coin example I get a blank white frame

**Comment by yhwang** [comment]
@Tomcli want to clarify if I understand it correctly. For this minimum setup, users need to have a single user kubeflow which is using tekton as pipeline engine. then follow the steps to finish the mlx setup? If this is the case, it would be good to list this as prerequisite and maybe point out the kubeflow single user installation instruction as reference link.

**Comment by Tomcli** [comment]
> @Tomcli want to clarify if I understand it correctly. For this minimum setup, users need to have a single user kubeflow which is using tekton as pipeline engine. then follow the steps to finish the mlx setup? If this is the case, it would be good to list this as prerequisite and maybe point out the kubeflow single user installation instruction as reference link.

No, this minimum setup only assumes users have Kubernetes running. They don't need to install anything else. This is designed to have MLX running with minimum dependencies so people can run it on dind and minikube for development.

The main goal for this instruction is to let the Acumos team deploy MLX on their local machine because their Acumos marketplace is also deployed locally.

**Comment by yhwang** [comment]
I see. thanks for the explanation. I got the picture now. I didn't look into the manifest you mentioned in the doc earlier.

**Comment by Tomcli** [comment]
> > > 1. Should users be able to launch pipelines and find the pipelinerun results?
> > 
> > 
> > 
> > 1. Yes, this is why #91 was the blocker. This is single user mode so everyone can run and view pipelines.
> 
> After a user launches a pipeline, where can they see the run results, graph, logs, etc? After I launched the Flip-coin example I get a blank white frame

It should work with your fixes. If you get a white frame that means the API is returning 500 errors

**Comment by ckadner** [comment]
> > > > 1. Should users be able to launch pipelines and find the pipelinerun results?
> > > 
> > > 
> > > 
> > > 1. Yes, this is why #91 was the blocker. This is single user mode so everyone can run and view pipelines.
> > 
> > 
> > After a user launches a pipeline, where can they see the run results, graph, logs, etc? After I launched the Flip-coin example I get a blank white frame
> 
> It should work with your fixes. If you get a white frame that means the API is returning 500 errors

The API returned with status `200`, response:
```JSON
{
  "run_url": "/runs/details/4dfe4833-637b-42fa-82ba-39efeb84b199"
}
```

**Comment by ckadner** [comment]
The `/pipeline` request returned this error:

```
You need to enable JavaScript to run this app.
```

**Comment by Tomcli** [comment]
> After launching the pipeline run, the MLX UI shows a white content frame:
> 
> * On Firefox, the `/pipeline` request returned this error:
> 
> ```
> You need to enable JavaScript to run this app.
> ```
> 
> * On Chrome, the `/pipeline` request returned this error:
> 
> ```
> Too many requests, please try again later.
> ```

@ckadner can you try it again on chrome? Also, for all the forwarded path there's a 1 minute rate limit over here.
https://github.com/machine-learning-exchange/mlx/blob/main/dashboard/origin-mlx/server/server.ts#L102-L110

If it happens too often, we may want to make it configurable.

**Comment by ckadner** [comment]
> > After launching the pipeline run, the MLX UI shows a white content frame:
> > 
> > * On Firefox, the `/pipeline` request returned this error:
> > 
> > ```
> > You need to enable JavaScript to run this app.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * On Chrome, the `/pipeline` request returned this error:
> > 
> > ```
> > Too many requests, please try again later.
> > ```
> 
> @ckadner can you try it again on chrome? Also, for all the forwarded path there's a 1 minute rate limit over here.
> https://github.com/machine-learning-exchange/mlx/blob/main/dashboard/origin-mlx/server/server.ts#L102-L110
> 
> If it happens too often, we may want to make it configurable.

On Chrome, after some time, same error as on Firefox:

```
You need to enable JavaScript to run this app.
```

**Comment by ckadner** [comment]
I'm pretty sure I do have JavaScript enabled on both Chrome and Firefox

**Comment by yhwang** [comment]
I tried it on a new IKS today and here is what I found:
- I like to use `LoadBalancer` to access the istio ingressgateway, so I created a gateway - `kubeflow-gateway` to handle the ingress. the virtualservice for mlx-ui and mlx-app are already there and they attach to `kubeflow-gateway`, I can get into the mlx-ui properly
- after I imported the boostrapper catalog, I can see all of the cards for pipelines, datasets, notebooks and etc.
- I can't launch the pipeline and seems it can't find the `/pipeline`. I got 404. I guess the reason is there is no virtualservice for the underlying ml-pipeline-ui service. The only virtualservice I saw are mlx-ui and mlx-app.

**Comment by Tomcli** [comment]
> I tried it on a new IKS today and here is what I found:
> 
> * I like to use `LoadBalancer` to access the istio ingressgateway, so I created a gateway - `kubeflow-gateway` to handle the ingress. the virtualservice for mlx-ui and mlx-app are already there and they attach to `kubeflow-gateway`, I can get into the mlx-ui properly
> * after I imported the boostrapper catalog, I can see all of the cards for pipelines, datasets, notebooks and etc.
> * I can't launch the pipeline and seems it can't find the `/pipeline`. I got 404. I guess the reason is there is no virtualservice for the underlying ml-pipeline-ui service. The only virtualservice I saw are mlx-ui and mlx-app.
> 
> _update_: I added `ml-pipeline-ui` virtualservice manually and I can launch a pipeline and see the pipeline run DAG properly.

Did you try with the new commands I put in? Sometimes the first kubctl apply, you may see some resources have errors saying the CRD is not ready.

**Comment by yhwang** [comment]
@Tomcli 
> Did you try with the new commands I put in? Sometimes the first kubctl apply, you may see some resources have errors saying the CRD is not ready.

yes, I used your new `while loop` command to do the installation

**Comment by Tomcli** [comment]
> @Tomcli
> 
> > Did you try with the new commands I put in? Sometimes the first kubctl apply, you may see some resources have errors saying the CRD is not ready.
> 
> yes, I used your new `while loop` command to do the installation

@yhwang when you run that command again, does it fix the issue?

**Comment by yhwang** [comment]
@Tomcli 
I still can't see the `ml-pipeline-ui` virtual service after I ran the command three times. And I check the output of `kustomize build example`. there is no ml-pipeline-ui vs.

**Comment by Tomcli** [comment]
@yhwang are you using the `mlx-single-user` branch? The overlay on that branch is different from master.

**Comment by yhwang** [comment]
your command: `git clone https://github.com/machine-learning-exchange/manifests -b mlx-single-user`

**Comment by yhwang** [comment]
I fetched the newest code from `https://github.com/machine-learning-exchange/manifests` and followed the instructions to finish the deployment again. it works for me now!

**Review by ckadner — APPROVED** [review]
Thanks Tommy. Works now.

/lgtm

**Pull request merged**
