### PR TITLE
Add yaml and yml support and fix hard fail on invalid component

### PR DESCRIPTION
**Pull request by drewbutlerbb4**
Resolves: #94
Resolves: #101
Related: #100

Fig hard-failing on invalid component templates.

### CODE REVIEW

**Comment by ckadner** [comment]
Thanks Andrew, are you planing to allow `upload_from_url` in a separate PR?

**Comment by drewbutlerbb4** [comment]
> Thanks Andrew, are you planing to allow `upload_from_url` in a separate PR?

Yes, I need to ask a few questions about how we want that to look before enabling it, since it will be an entirely different way to upload.

**Comment by ckadner** [comment]
@drewbutlerbb4 -- did you already build this into a `mlx-ui` image I can use to test your changes?

**Comment by ckadner** [comment]
> "Enter a name and upload a .tgz, .tar.gz, .yaml, or .yml file to **_create_** a new dataset."

Can we replace the word "**_create_**" with the word "**_register_**"?

**Review by ckadner — APPROVED** [review]
/lgtm

**Comment by ckadner** [comment]
I tested on your Docker image. Looks good. But we should work on the error messages returned for invalid YAML or missing elements of the defined metadata schema.

**Pull request merged**
