### PR TITLE
Modified the way sed version is set

### PR DESCRIPTION
**Pull request by krishnakumar27**
machine-learning-exchange/mlx#301

Updated the way sed is called depending on whether it was a MacOS version or BSD version of sed

@ckadner FYI

### CODE REVIEW

**Review by ckadner — COMMENTED** [review]
Thank you Krishna, did you test the two scripts?
- for `codegen.sh` run it on the main repo clone and on the clone of your forks with the changes and use a file/directory comparison tool to make sure the outcome is the same before and after your changes. Running `generate_code.sh` (which is calling `codegen.sh`) should produce no changes (`git status` -> clean)
- for `add_license_header.sh`, same thing, clone main repo and compare to your changed script. Here you would remove license header from a Python script, a JavaScript, a HTML, a YAML file and see it gets generated correctly

**Comment by ckadner** [comment]
Oh, and you need to sign-off your commits to make the DCO checks pass :-)

**Comment by krishnakumar27** [comment]
@ckadner I have tested both the scripts in both linux and mac. They seem to work as expected.

**Review by ckadner — APPROVED** [review]
Thanks @krishnakumar27

**Comment by ckadner** [comment]
Please fix the failing DCO check by (squashing and) signing your commits.

**Comment by krishnakumar27** [comment]
@ckadner I just did the DCO signoff

**Comment by ckadner** [comment]
Hi @krishnakumar27 -- I see a lot of unrelated commits in your PR since you used your forks `main` branch for your changes and then later merged the upstream `main`. I don't want to merge all of those other commits. Could you roll back your merge commits (`git reset HEAD~10` -- go 10 commits back) and instead of doing merges, do a [rebase](https://betterprogramming.pub/differences-between-git-merge-and-rebase-and-why-you-should-care-ae41d96237b6) the changes you made for this PR in your forks `main`? Though it looks like your actual code changes are in a commit somewhere in the middle of the 9 unrelated commits, so it might be easier to close this PR and create a new PR from a new feature branch (created after you update your forks main with the upstream main.

**Comment by ckadner** [comment]
Hi @krishnakumar27 -- I resolved the merge conflict and did a dry-run to test squashing-merging your PR. Seems Github figured out that only 2 files were changed. So all is good. Please create a feature branch for your next contribution instead of committing directly to the `main` branch of your mlx fork :-)

**Comment by krishnakumar27** [comment]
@ckadner Alright, yeah I was working with a feature branch in my fork, but I merged it to my main before creating a PR. I will create a PR directly from there the next time. Thank you

**Pull request merged**
