### PR TITLE
Only show settings link for admin role

### PR DESCRIPTION
**Pull request by yhwang**
Read the cookie value to distinguish a user's role and
only show the settings link to users with admin role.

Signed-off-by: Yihong Wang <yh.wang@ibm.com>

### CODE REVIEW

**Comment by yhwang** [comment]
@Tomcli @drewbutlerbb4 @ckadner need your help to identify what resources/pages/links that are only accessible for admin role. In this PR, I only added the restriction to `MLX Settgings` link, which means only an admin can see this link. And this is only in UX. I will add enforcement check on server side in a separated PR.

**Comment by Tomcli** [comment]
For anonymous users, they should only make GET requests, all the POST/PUT/DELETE requests should be blocked.

**Comment by Tomcli** [comment]
For the UX, we should remove all the run page for anonymous users

**Comment by ckadner** [comment]
> For anonymous users, they should only make GET requests, all the POST/PUT/DELETE requests should be blocked.

Besides blocking POST/PUT/DELETE, is there a set of rules which defines what URLs or URL segments are allowed/restricted?

**Comment by yhwang** [comment]
> For anonymous users, they should only make GET requests, all the POST/PUT/DELETE requests should be blocked.
Got it. However, this kind of restrictions would be enforced on server side. The point is even the function is disabled on browser, we still need to guard server side APIs from accessing by anonymous users.
On browser side, we can either remove or gray out the links/buttons/pages.

**Comment by Tomcli** [comment]
> > For anonymous users, they should only make GET requests, all the POST/PUT/DELETE requests should be blocked.
> 
> Besides blocking POST/PUT/DELETE, is there a set of rules which defines what URLs or URL segments are allowed/restricted?

Everything related to settings should also be blocked.

**Comment by yhwang** [comment]
@Tomcli, @drewbutlerbb4 , @ckadner  more links and pages are disabled based on your suggestions. please review the change again. Thanks

**Comment by ckadner** [comment]
@yhwang -- did you build a Docker image with your changes that I can pull to test?

**Comment by yhwang** [comment]
@ckadner yes: yihongwang/mlx-ui:dev
it also contains the `/os/login` path which serves login

**Review by ckadner — APPROVED** [review]
in the context of Docker Compose (Quickstart) your changes work well

**Comment by ckadner** [comment]
@drewbutlerbb4 -- if you are okay with these changes, please go ahead and merge this PR. Thanks.

**Pull request merged**
